Importing dependencies

In [89]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

Data collection and analysis

In [90]:
data=pd.read_csv(
    "diabetes.csv"
)

data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [91]:
"printing the first 5 rows"
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [92]:
"Number of rows and column in an dataset"
data.shape

(768, 9)

In [93]:
"Statastical property of the data"

data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [94]:
"Information of the dataset"

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [95]:
"Values count of diabetic and non-diabetic "
data["Outcome"].value_counts()

"here 1 ---> diabetic and 0 ---> non-diabetic"

'here 1 ---> diabetic and 0 ---> non-diabetic'

In [96]:
data.groupby("Outcome").mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [97]:
"Saperating the data labels"

X = data.drop(columns = 'Outcome')
y=data["Outcome"]

In [98]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [99]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [100]:
scaler=StandardScaler()

standard_scaler=scaler.fit_transform(X)

print(standard_scaler)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [101]:
X=standard_scaler
Y=data["Outcome"]

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=42, stratify=Y, random_state=2)

print(X.shape)
print(X_train.shape)
print(X_test.shape)

(768, 8)
(726, 8)
(42, 8)

In [102]:
classfier=svm.SVC(kernel="linear")

classfier.fit(X_train, Y_train)

SVC(kernel='linear')

In [103]:
"Accuracy score of training data"
x_pred=classfier.predict(X_train)
x_accuracy=accuracy_score(x_pred,Y_train)

In [104]:
print("Accury score of training data is :",x_accuracy)

Accury score of training data is : 0.7796143250688705

In [105]:
"accuracy_score of testing data"

x_test_pred=classfier.predict(X_test)
x_test_accuracy=accuracy_score(x_test_pred,Y_test)

In [106]:
"Accuray score of testing data"
print("Accuracy score of tesing data is : ",x_test_accuracy)

Accuracy score of tesing data is :  0.8095238095238095

In [ ]:
preg=float(input("Enter pregnencies: "))
glucose=float(input("Enter glucose: "))
bp=float(input("Enter Blood Pressure: "))
skin=float(input("Enter Skin Thicknes: "))
insulin=float(input("Enter Insuline: "))
bmi=float(input("Enter BMI Score: "))
dpf=float(input("Enter Diabetes Pedigree Function: "))
age= float(input("Enter Age: "))

input_data=np.array([preg, glucose, bp, skin, insulin, bmi, dpf,age])

input_data=input_data.reshape(1, -1)

print(input_data)

std_data=scaler.transform(input_data)
prediction=classfier.predict(std_data)

print(prediction)

if prediction[0]==1:
    print("The patient diabetic")
else:
    print("The patient is not diabetic")

[[  5.  166.   72.   19.  175.   26.    0.5  51. ]]
[1]

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(